### ISSUE TITLE
ImportError: cannot import name frombuffer_empty

### ISSUE THREAD

**Issue by jtdoepke** [ClimbsRocks/auto_ml#313]
I get the following import error with `scikit-learn==0.19.0`.

```python
Traceback (most recent call last):   
  File "test.py", line 1, in <module>                                      
    from auto_ml import Predictor    
  File "/home/jdoepke/Development/auto_ml_test/venv/lib/python2.7/site-packages/auto_ml/__init__.py", line 6, in <module>
    from auto_ml.predictor import Predictor                                
  File "/home/jdoepke/Development/auto_ml_test/venv/lib/python2.7/site-packages/auto_ml/predictor.py", line 32, in <module>
    from auto_ml import DataFrameVectorizer                                
  File "/home/jdoepke/Development/auto_ml_test/venv/lib/python2.7/site-packages/auto_ml/DataFrameVectorizer.py", line 11, in <module>
    from sklearn.utils.fixes import frombuffer_empty                       
ImportError: cannot import name frombuffer_empty
```

It looks like they've [dropped this function](https://github.com/scikit-learn/scikit-learn/commit/65792205887c37316dd7da348179652d13e79b78) along with support for`numpy<1.8`.

**Comment by ClimbsRocks** [comment]
oh sweet! i didn't realize they'd cut a new release. 

bummer that they cut that function without a deprecation warning. 

i'll see if i can fix this up today. thanks for letting me know! in the meantime, everything should work fine on `scikit-learn==0.18.2` as a workaround. 

out of curiosity, what was your favorite part of the new release?

**Comment by omarcr** [comment]
This is still not fixed :(  when will this be fixed? Cheers.

**Comment by ClimbsRocks** [comment]
@omarcr yeah, it ended up being a more involved fix than i expected, because a couple other libraries also chose that week to release their own new versions that broke existing codebases. then i left for the desert for vacation for a while without internet access :) 

it's fixed now, and available on pypi as version 2.6.0!
